
package com.tigo.sendnotification;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SendNotificationDirectBinding1.1QSService", targetNamespace = "http://www.tigo.com/SendNotification", wsdlLocation = "http://osb-test.telecel.net.py/sbresource?PROXY/SatelliteSystems/SendNotification/PS/PS_SendNotification")
public class SendNotificationDirectBinding11QSService
    extends Service
{

    private final static URL SENDNOTIFICATIONDIRECTBINDING11QSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.tigo.sendnotification.SendNotificationDirectBinding11QSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.tigo.sendnotification.SendNotificationDirectBinding11QSService.class.getResource(".");
            url = new URL(baseUrl, "http://osb-test.telecel.net.py/sbresource?PROXY/SatelliteSystems/SendNotification/PS/PS_SendNotification");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://osb-test.telecel.net.py/sbresource?PROXY/SatelliteSystems/SendNotification/PS/PS_SendNotification', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SENDNOTIFICATIONDIRECTBINDING11QSSERVICE_WSDL_LOCATION = url;
    }

    public SendNotificationDirectBinding11QSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendNotificationDirectBinding11QSService() {
        super(SENDNOTIFICATIONDIRECTBINDING11QSSERVICE_WSDL_LOCATION, new QName("http://www.tigo.com/SendNotification", "SendNotificationDirectBinding1.1QSService"));
    }

    /**
     * 
     * @return
     *     returns SendNotification
     */
    @WebEndpoint(name = "SendNotificationDirectBinding1.1QSPort")
    public SendNotification getSendNotificationDirectBinding11QSPort() {
        return super.getPort(new QName("http://www.tigo.com/SendNotification", "SendNotificationDirectBinding1.1QSPort"), SendNotification.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendNotification
     */
    @WebEndpoint(name = "SendNotificationDirectBinding1.1QSPort")
    public SendNotification getSendNotificationDirectBinding11QSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tigo.com/SendNotification", "SendNotificationDirectBinding1.1QSPort"), SendNotification.class, features);
    }

}
