
package com.tigo.sendnotification;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.tigo.sendnotificationrequest.v1.SendNotificationRequest;
import com.tigo.sendnotificationresponse.v1.SendNotificationResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SendNotification", targetNamespace = "http://www.tigo.com/SendNotification")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.tigo.sendnotificationrequest.v1.ObjectFactory.class,
    com.tigo.sendnotificationresponse.v1.ObjectFactory.class,
    com.tigo.core.common.header.request.v1.ObjectFactory.class,
    com.tigo.core.common.header.response.v1.ObjectFactory.class,
    com.tigo.core.common.v1.ObjectFactory.class,
    com.tigo.parametertype.v1.ObjectFactory.class,
    com.tigo.sendnotification.v1.ObjectFactory.class,
    com.tigo.core.common.error.v1.ObjectFactory.class
})
public interface SendNotification {


    /**
     * 
     * @param payload
     * @return
     *     returns com.tigo.sendnotificationresponse.v1.SendNotificationResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "SendNotificationResponse", targetNamespace = "http://www.tigo.com/SendNotificationResponse/V1", partName = "payload")
    public SendNotificationResponse process(
        @WebParam(name = "SendNotificationRequest", targetNamespace = "http://www.tigo.com/SendNotificationRequest/V1", partName = "payload")
        SendNotificationRequest payload);

}
