package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonView;
import org.hibernate.validator.constraints.Length;
import py.com.global.spm.domain.utils.ScopeViews;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Beneficiary generated by hbm2java
 */
@Entity
@Table(name = "BENEFICIARY" , uniqueConstraints = @UniqueConstraint(columnNames = {"PHONENUMBER_CHR", "IDCOMPANY_PK"},
		name = "UNIQUEBENEFICIARY"), indexes = {@Index(columnList = "PHONENUMBER_CHR",name = "index_beneficiary")})
public class Beneficiary implements Serializable {


	private static final long serialVersionUID = 1L;
	@JsonView(ScopeViews.Basics.class)
	private Long idbeneficiaryPk;
	@JsonView(ScopeViews.Basics.class)
	private String phonenumberChr;
	@JsonView(ScopeViews.Basics.class)
	private String beneficiarynameChr;
	@JsonView(ScopeViews.Basics.class)
	private String beneficiarylastnameChr;
	@JsonView(ScopeViews.Details.class)
	private Company company;
	@JsonView(ScopeViews.Basics.class)
	private Long idcompanyPk;
	@JsonView(ScopeViews.Details.class)
	private String emailChr;
	@JsonView(ScopeViews.Details.class)
	private String stateChr;
	@JsonView(ScopeViews.Details.class)
	private Date creationdateTim;
	@JsonView(ScopeViews.Basics.class)
	private String currencyChr;
	@JsonView(ScopeViews.Basics.class)
	private String rolspChr;
	@JsonView(ScopeViews.Basics.class)
	private String walletChr;
	@JsonView(ScopeViews.Details.class)
	private boolean notifyemailNum;
	@JsonView(ScopeViews.Details.class)
	private boolean notifysmsNum=true;
	@JsonView(ScopeViews.Details.class)
	private String subscriberciChr;
	@JsonView(ScopeViews.NoBasics.class)
	private String generico1Chr;
	@JsonView(ScopeViews.NoBasics.class)
	private String generico2Chr;
	@JsonView(ScopeViews.NoBasics.class)
	private String generico3Chr;
	
	private transient boolean selected=false;
	@Transient
	private transient BigDecimal amount;
	@JsonView(ScopeViews.NoBasics.class)
	private Set<Paymentorderdetail> paymentorderdetails = new HashSet<Paymentorderdetail>(
			0);
	@JsonView(ScopeViews.NoBasics.class)
	private Set<Draftdetail> draftdetails = new HashSet<Draftdetail>(0);

	public Beneficiary() {
	}

	public Beneficiary(Long idbeneficiaryPk, String phonenumberChr,
			String beneficiarynameChr, String stateChr,
			Date creationdateTim) {
		this.idbeneficiaryPk = idbeneficiaryPk;
		this.phonenumberChr = phonenumberChr;
		this.beneficiarynameChr = beneficiarynameChr;
		this.stateChr = stateChr;
		this.creationdateTim = creationdateTim;
	}

	public Beneficiary(Long idbeneficiaryPk, String phonenumberChr,
			String beneficiarynameChr, String beneficiarylastnameChr,
			String emailChr, String stateChr, Date creationdateTim,
			Set<Paymentorderdetail> paymentorderdetails,
			Set<Draftdetail> draftdetails) {
		this.idbeneficiaryPk = idbeneficiaryPk;
		this.phonenumberChr = phonenumberChr;
		this.beneficiarynameChr = beneficiarynameChr;
		this.beneficiarylastnameChr = beneficiarylastnameChr;
		this.emailChr = emailChr;
		this.stateChr = stateChr;
		this.creationdateTim = creationdateTim;
		this.paymentorderdetails = paymentorderdetails;
		this.draftdetails = draftdetails;
		/*
		this.generico1Chr = generico1Chr;
		this.generico2Chr = generico2Chr;
		this.generico3Chr = generico3Chr;
		*/
	}

	@Id
	@Column(name = "IDBENEFICIARY_PK", unique = true, nullable = false, precision = 22, scale = 0)
	@NotNull
	@SequenceGenerator(name="BENEFICIARY_SEQ_GEN",sequenceName="BENEFICIARY_SEQ", allocationSize=1)
	@GeneratedValue(generator="BENEFICIARY_SEQ_GEN")
	public Long getIdbeneficiaryPk() {
		return this.idbeneficiaryPk;
	}

	public void setIdbeneficiaryPk(Long idbeneficiaryPk) {
		this.idbeneficiaryPk = idbeneficiaryPk;
	}

	@Column(name = "PHONENUMBER_CHR", unique = false, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getPhonenumberChr() {
		return this.phonenumberChr;
	}

	public void setPhonenumberChr(String phonenumberChr) {
		this.phonenumberChr = phonenumberChr;
	}

	@Column(name = "BENEFICIARYNAME_CHR",  length = 50)
	//@Pattern(regex=".*[^\\s].*", message="Ingres� solo espacios en blanco")
	@Length(max = 50)
	public String getBeneficiarynameChr() {
		return this.beneficiarynameChr;
	}

	public void setBeneficiarynameChr(String beneficiarynameChr) {
		this.beneficiarynameChr = beneficiarynameChr;
	}

	@Column(name = "BENEFICIARYLASTNAME_CHR", length = 50)
	@Length(max = 50)
	public String getBeneficiarylastnameChr() {
		return this.beneficiarylastnameChr;
	}

	public void setBeneficiarylastnameChr(String beneficiarylastnameChr) {
		this.beneficiarylastnameChr = beneficiarylastnameChr;
	}
	
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCOMPANY_PK", nullable = false)
	@NotNull
	public Company getCompany() {
		return company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "IDCOMPANY_PK", insertable = false, updatable = false)
	public Long getIdcompanyPk() {
		return idcompanyPk;
	}

	public void setIdcompanyPk(Long idcompanyPk) {
		this.idcompanyPk = idcompanyPk;
	}
	@Column(name = "EMAIL_CHR", length = 50)
	@Length(max = 50)
	public String getEmailChr() {
		return this.emailChr;
	}

	public void setEmailChr(String emailChr) {
		this.emailChr = emailChr;
	}

	@Column(name = "STATE_CHR", nullable = false, length = 2)
	public String getStateChr() {
		return this.stateChr;
	}

	public void setStateChr(String stateChr) {
		this.stateChr = stateChr;
	}

	@Column(name = "CREATIONDATE_TIM", nullable = false)
	@NotNull
	public Date getCreationdateTim() {
		return this.creationdateTim;
	}

	public void setCreationdateTim(Date creationdateTim) {
		this.creationdateTim = creationdateTim;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "beneficiary")
	public Set<Paymentorderdetail> getPaymentorderdetails() {
		return this.paymentorderdetails;
	}

	public void setPaymentorderdetails(
			Set<Paymentorderdetail> paymentorderdetails) {
		this.paymentorderdetails = paymentorderdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "beneficiary")
	public Set<Draftdetail> getDraftdetails() {
		return this.draftdetails;
	}

	public void setDraftdetails(Set<Draftdetail> draftdetails) {
		this.draftdetails = draftdetails;
	}

	
	@Transient
	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}

	@Column(name="NOTIFYEMAIL_NUM", precision=1,scale=0)
	public boolean isNotifyemailNum() {
		return notifyemailNum;
	}

	public void setNotifyemailNum(boolean notifyemailNum) {
		this.notifyemailNum = notifyemailNum;
	}
	@Column(name="NOTIFYSMS_NUM", precision=1,scale=0)
	public boolean isNotifysmsNum() {
		return notifysmsNum;
	}

	public void setNotifysmsNum(boolean notifysmsNum) {
		this.notifysmsNum = notifysmsNum;
	}

	@Transient
	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	@Column(name = "CURRENCY_CHR", length = 20)
	public String getCurrencyChr() {
		return currencyChr;
	}

	public void setCurrencyChr(String currencyChr) {
		this.currencyChr = currencyChr;
	}
	@Column(name = "ROLSP_CHR", length = 20)
	public String getRolspChr() {
		return rolspChr;
	}

	public void setRolspChr(String rolspChr) {
		this.rolspChr = rolspChr;
	}

	@Column(name = "WALLET_CHR", length = 20)
	public String getWalletChr() {
		return walletChr;
	}

	public void setWalletChr(String walletChr) {
		this.walletChr = walletChr;
	}

	@Column(name = "SUBSCRIBERCI_CHR", length = 20)
	public String getSubscriberciChr() {
		return subscriberciChr;
	}

	public void setSubscriberciChr(String subscriberciChr) {
		this.subscriberciChr = subscriberciChr;
	}

	@Column(name = "GENERICO1_CHR", length = 500)
	public String getGenerico1Chr() {
		return generico1Chr;
	}

	public void setGenerico1Chr(String generico1Chr) {
		this.generico1Chr = generico1Chr;
	}
	
	@Column(name = "GENERICO2_CHR", length = 500)
	public String getGenerico2Chr() {
		return generico2Chr;
	}

	public void setGenerico2Chr(String generico2Chr) {
		this.generico2Chr = generico2Chr;
	}
	
	@Column(name = "GENERICO3_CHR", length = 500)
	public String getGenerico3Chr() {
		return generico3Chr;
	}

	public void setGenerico3Chr(String generico3Chr) {
		this.generico3Chr = generico3Chr;
	}

	@Override
	public String toString() {
		return "Beneficiary{" +
				"idbeneficiaryPk=" + idbeneficiaryPk +
				", phonenumberChr='" + phonenumberChr + '\'' +
				", beneficiarynameChr='" + beneficiarynameChr + '\'' +
				", beneficiarylastnameChr='" + beneficiarylastnameChr + '\'' +
				", company=" + company +
				", emailChr='" + emailChr + '\'' +
				", stateChr=" + stateChr +
				", creationdateTim=" + creationdateTim +
				", currencyChr='" + currencyChr + '\'' +
				", rolspChr='" + rolspChr + '\'' +
				", walletChr='" + walletChr + '\'' +
				", notifyemailNum=" + notifyemailNum +
				", notifysmsNum=" + notifysmsNum +
				", subscriberciChr='" + subscriberciChr + '\'' +
				'}';
	}
}
