package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonView;
import org.hibernate.validator.constraints.Length;
import py.com.global.spm.domain.utils.ScopeViews;
import py.com.global.spm.domain.audit.EntityAuditEventListener;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "COMPANY")
@EntityListeners(EntityAuditEventListener.class)
public class Company implements Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = -2766915417179468494L;
	@JsonView({ScopeViews.Basics.class})
	private Long idcompanyPk;
	@JsonView({ScopeViews.Basics.class})
	private String companynameChr;
	@JsonView({ScopeViews.Details.class})
	private Date creationdateTim;
	@JsonView({ScopeViews.Details.class})
	private String stateChr;
	@JsonView({ScopeViews.Details.class})
	private String descriptionChr;
	@JsonView({ScopeViews.Details.class})
	private String contactnameChr;
	@JsonView({ScopeViews.Details.class})
	private String emailChr;
	@JsonView({ScopeViews.Details.class})
	private String phonenumberChr;
	@JsonView({ScopeViews.Details.class})
	private Long trxdaylimitNum;
	@JsonView({ScopeViews.Details.class})
	private Long trxmonthlimitNum;
	@JsonView({ScopeViews.Details.class})
	private Long trxtotallimitNum;
	@JsonView({ScopeViews.Details.class})
	private Long trxdaycountNum;
	@JsonView({ScopeViews.Details.class})
	private Long trxmonthcountNum;
	@JsonView({ScopeViews.Details.class})
	private Long trxtotalcountNum;
	@JsonView({ScopeViews.Details.class})
	private Date lastopdateTim;
	@JsonIgnore
	private String mtsfield1Chr;
	@JsonIgnore
	private String mtsfield2Chr;
	@JsonIgnore
	private String mtsfield3Chr;
	@JsonIgnore
	private String mtsfield4Chr;
	private String mtsfield5Chr;
	@JsonIgnore
	private Integer priority;
	@JsonView({ScopeViews.Details.class})
	private Double percentcommissionNum;
	@JsonView({ScopeViews.NoBasics.class})
	private String mtspasswordChr;
//	@JsonView({ScopeViews.NoBasics.class})
//	private Set<Beneficiary> beneficiaries = new HashSet<Beneficiary>(0);
	@JsonView({ScopeViews.NoBasics.class})
	@JsonBackReference
	private Set<Workflow> workflows = new HashSet<Workflow>(0);
	@JsonView({ScopeViews.NoBasics.class})
	@JsonBackReference
	private Set<User> users = new HashSet<User>(0);
	@JsonView({ScopeViews.NoBasics.class})
	@JsonBackReference
	private Set<Paymentorder> paymentorders = new HashSet<Paymentorder>(0);
	@JsonBackReference
	@JsonView({ScopeViews.NoBasics.class})
	private Set<Approval> approvals = new HashSet<Approval>(0);
	@JsonView({ScopeViews.NoBasics.class})
	@JsonBackReference
	private Set<Logmessage> logmessages = new HashSet<Logmessage>(0);
	@JsonView({ScopeViews.NoBasics.class})
	@JsonBackReference
	private Set<Logmtsrev> logmtsrevs = new HashSet<Logmtsrev>(0);
	@JsonView({ScopeViews.NoBasics.class})
	@JsonBackReference
	private Set<Logpayment> logpayments = new HashSet<Logpayment>(0);
	@JsonView({ScopeViews.NoBasics.class})
	@JsonBackReference
	private Set<Draft> drafts = new HashSet<Draft>(0);
	@JsonView({ScopeViews.NoBasics.class})
	@JsonBackReference
	private Set<Logmts> logmtses = new HashSet<Logmts>(0);
	@JsonView({ScopeViews.NoBasics.class})
	@JsonBackReference
	private Set<Logdraftop> logdraftops = new HashSet<Logdraftop>(0);

	public Company() {
	}

	public Company(Long idcompanyPk, String companynameChr,
			Date creationdateTim, String stateChr, String contactnameChr,
			Long trxdaylimitNum, Long trxmonthlimitNum, Long trxtotallimitNum,
			Long trxdaycountNum, Long trxmonthcountNum, Long trxtotalcountNum) {
		this.idcompanyPk = idcompanyPk;
		this.companynameChr = companynameChr;
		this.creationdateTim = creationdateTim;
		this.stateChr = stateChr;
		this.contactnameChr = contactnameChr;
		this.trxdaylimitNum = trxdaylimitNum;
		this.trxmonthlimitNum = trxmonthlimitNum;
		this.trxtotallimitNum = trxtotallimitNum;
		this.trxdaycountNum = trxdaycountNum;
		this.trxmonthcountNum = trxmonthcountNum;
		this.trxtotalcountNum = trxtotalcountNum;
	}

	public Company(Long idcompanyPk, String companynameChr,
			Date creationdateTim, String stateChr, String descriptionChr,
			String contactnameChr, String emailChr, String phonenumberChr,
			Long trxdaylimitNum, Long trxmonthlimitNum, Long trxtotallimitNum,
			Long trxdaycountNum, Long trxmonthcountNum, Long trxtotalcountNum,
			Date lastopdateTim, String mtsbandChr, String mtswallettypeChr,
			String mtsrolChr, Set<Workflow> workflows, Set<User> users,
			Set<Paymentorder> paymentorders, Set<Approval> approvals,
			Set<Logmessage> logmessages, Set<Logmtsrev> logmtsrevs,
			Set<Logpayment> logpayments, Set<Draft> drafts,
			Set<Logmts> logmtses, Set<Logdraftop> logdraftops) {
		this.idcompanyPk = idcompanyPk;
		this.companynameChr = companynameChr;
		this.creationdateTim = creationdateTim;
		this.stateChr = stateChr;
		this.descriptionChr = descriptionChr;
		this.contactnameChr = contactnameChr;
		this.emailChr = emailChr;
		this.phonenumberChr = phonenumberChr;
		this.trxdaylimitNum = trxdaylimitNum;
		this.trxmonthlimitNum = trxmonthlimitNum;
		this.trxtotallimitNum = trxtotallimitNum;
		this.trxdaycountNum = trxdaycountNum;
		this.trxmonthcountNum = trxmonthcountNum;
		this.trxtotalcountNum = trxtotalcountNum;
		this.lastopdateTim = lastopdateTim;
		this.workflows = workflows;
		this.users = users;
		this.paymentorders = paymentorders;
		this.approvals = approvals;
		this.logmessages = logmessages;
		this.logmtsrevs = logmtsrevs;
		this.logpayments = logpayments;
		this.drafts = drafts;
		this.logmtses = logmtses;
		this.logdraftops = logdraftops;
	}

	@Id
	@Column(name = "IDCOMPANY_PK", unique = true, nullable = false, precision = 22, scale = 0)
	@NotNull
	@SequenceGenerator(name = "COMPANY_SEQ_GEN", sequenceName = "COMPANY_SEQ", allocationSize = 1)
	@GeneratedValue(generator = "COMPANY_SEQ_GEN")
	public Long getIdcompanyPk() {
		return this.idcompanyPk;
	}

	public void setIdcompanyPk(Long idcompanyPk) {
		this.idcompanyPk = idcompanyPk;
	}

	@Column(name = "COMPANYNAME_CHR", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getCompanynameChr() {
		return this.companynameChr;
	}

	public void setCompanynameChr(String companynameChr) {
		this.companynameChr = companynameChr;
	}

	@Column(name = "CREATIONDATE_TIM", nullable = false)
	@NotNull
	public Date getCreationdateTim() {
		return this.creationdateTim;
	}

	public void setCreationdateTim(Date creationdateTim) {
		this.creationdateTim = creationdateTim;
	}

	@Column(name = "STATE_CHR", nullable = false, length = 2)
	public String getStateChr() {
		return this.stateChr;
	}

	public void setStateChr(String stateChr) {
		this.stateChr = stateChr;
	}

	@Column(name = "DESCRIPTION_CHR", length = 200)
	@Length(max = 200)
	public String getDescriptionChr() {
		return this.descriptionChr;
	}

	public void setDescriptionChr(String descriptionChr) {
		this.descriptionChr = descriptionChr;
	}

	@Column(name = "CONTACTNAME_CHR", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getContactnameChr() {
		return this.contactnameChr;
	}

	public void setContactnameChr(String contactnameChr) {
		this.contactnameChr = contactnameChr;
	}

	@Column(name = "EMAIL_CHR", length = 50)
	@Length(max = 50)
	public String getEmailChr() {
		return this.emailChr;
	}

	public void setEmailChr(String emailChr) {
		this.emailChr = emailChr;
	}

	@Column(name = "PHONENUMBER_CHR", length = 20)
	@Length(max = 20)
	public String getPhonenumberChr() {
		return this.phonenumberChr;
	}

	public void setPhonenumberChr(String phonenumberChr) {
		this.phonenumberChr = phonenumberChr;
	}

	@Column(name = "TRXDAYLIMIT_NUM", nullable = false, precision = 10, scale = 0)
	public Long getTrxdaylimitNum() {
		return this.trxdaylimitNum;
	}

	public void setTrxdaylimitNum(Long trxdaylimitNum) {
		this.trxdaylimitNum = trxdaylimitNum;
	}

	@Column(name = "TRXMONTHLIMIT_NUM", nullable = false, precision = 10, scale = 0)
	public Long getTrxmonthlimitNum() {
		return this.trxmonthlimitNum;
	}

	public void setTrxmonthlimitNum(Long trxmonthlimitNum) {
		this.trxmonthlimitNum = trxmonthlimitNum;
	}

	@Column(name = "TRXTOTALLIMIT_NUM", nullable = false, precision = 10, scale = 0)
	public Long getTrxtotallimitNum() {
		return this.trxtotallimitNum;
	}

	public void setTrxtotallimitNum(Long trxtotallimitNum) {
		this.trxtotallimitNum = trxtotallimitNum;
	}

	@Column(name = "TRXDAYCOUNT_NUM", nullable = false, precision = 10, scale = 0)
	public Long getTrxdaycountNum() {
		return this.trxdaycountNum;
	}

	public void setTrxdaycountNum(Long trxdaycountNum) {
		this.trxdaycountNum = trxdaycountNum;
	}

	@Column(name = "TRXMONTHCOUNT_NUM", nullable = false, precision = 10, scale = 0)
	public Long getTrxmonthcountNum() {
		return this.trxmonthcountNum;
	}

	public void setTrxmonthcountNum(Long trxmonthcountNum) {
		this.trxmonthcountNum = trxmonthcountNum;
	}

	@Column(name = "TRXTOTALCOUNT_NUM", nullable = false, precision = 10, scale = 0)
	public Long getTrxtotalcountNum() {
		return this.trxtotalcountNum;
	}

	public void setTrxtotalcountNum(Long trxtotalcountNum) {
		this.trxtotalcountNum = trxtotalcountNum;
	}

	@Column(name = "LASTOPDATE_TIM")
	public Date getLastopdateTim() {
		return this.lastopdateTim;
	}

	public void setLastopdateTim(Date lastopdateTim) {
		this.lastopdateTim = lastopdateTim;
	}

	@Column(name = "PRIORITY", length = 1)
	public Integer getPriority() {
		return priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@JsonIgnore
	@Column(name = "MTSFIELD1_CHR", length = 30)
	@Length(max = 30)
	public String getMtsbandChr() {
		return this.mtsfield1Chr;
	}

	public void setMtsbandChr(String mtsfield1Chr) {
		this.mtsfield1Chr = mtsfield1Chr;
	}

	@JsonIgnore
	@Column(name = "MTSFIELD2_CHR", length = 30)
	@Length(max = 30)
	public String getMtswallettypeChr() {
		return this.mtsfield2Chr;
	}

	public void setMtswallettypeChr(String mtswallettypeChr) {
		this.mtsfield2Chr = mtswallettypeChr;
	}

	@JsonIgnore
	@Column(name = "MTSFIELD3_CHR", length = 50)
	@Length(max = 50)
	public String getMtspasswordChr() {
		return mtsfield3Chr;
	}

	public void setMtspasswordChr(String mtspasswordChr) {
		this.mtsfield3Chr = mtspasswordChr;
	}

	@JsonIgnore
	@Column(name = "MTSFIELD4_CHR", length = 30)
	@Length(max = 30)
	public String getMtsrolbindChr() {
		return mtsfield4Chr;
	}

	public void setMtsrolbindChr(String mtsrolbindChr) {
		this.mtsfield4Chr = mtsrolbindChr;
	}

	@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
	@Column(name = "MTSFIELD5_CHR", length = 30)
	@Length(max = 30)
	public String getMtsusrChr() {
		return mtsfield5Chr;
	}

	public void setMtsusrChr(String mtsusrChr) {
		this.mtsfield5Chr = mtsusrChr;
	}

	@Column(name = "PERCENTCOMMISSION_NUM", nullable = false, precision = 12, scale = 3)
	@NotNull
	public Double getPercentcommissionNum() {
		return percentcommissionNum;
	}

	public void setPercentcommissionNum(Double percentcommissionNum) {
		this.percentcommissionNum = percentcommissionNum;
	}

	@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
	@Column(name = "MTSPASSWORD_CHR", length = 300)
	public String getMtspasswordChr01() {
		return mtspasswordChr;
	}

	public void setMtspasswordChr01(String mtspasswordChr) {
		this.mtspasswordChr = mtspasswordChr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Workflow> getWorkflows() {
		return this.workflows;
	}

	public void setWorkflows(Set<Workflow> workflows) {
		this.workflows = workflows;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Paymentorder> getPaymentorders() {
		return this.paymentorders;
	}

	public void setPaymentorders(Set<Paymentorder> paymentorders) {
		this.paymentorders = paymentorders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Approval> getApprovals() {
		return this.approvals;
	}

	public void setApprovals(Set<Approval> approvals) {
		this.approvals = approvals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Logmessage> getLogmessages() {
		return this.logmessages;
	}

	public void setLogmessages(Set<Logmessage> logmessages) {
		this.logmessages = logmessages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Logmtsrev> getLogmtsrevs() {
		return this.logmtsrevs;
	}

	public void setLogmtsrevs(Set<Logmtsrev> logmtsrevs) {
		this.logmtsrevs = logmtsrevs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Logpayment> getLogpayments() {
		return this.logpayments;
	}

	public void setLogpayments(Set<Logpayment> logpayments) {
		this.logpayments = logpayments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Draft> getDrafts() {
		return this.drafts;
	}

	public void setDrafts(Set<Draft> drafts) {
		this.drafts = drafts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Logmts> getLogmtses() {
		return this.logmtses;
	}

	public void setLogmtses(Set<Logmts> logmtses) {
		this.logmtses = logmtses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Logdraftop> getLogdraftops() {
		return this.logdraftops;
	}

	public void setLogdraftops(Set<Logdraftop> logdraftops) {
		this.logdraftops = logdraftops;
	}



	@Override
	public String toString() {
		return "Company [idcompanyPk=" + idcompanyPk + ", companynameChr="
				+ companynameChr + ", creationdateTim=" + creationdateTim
				+ ", stateChr=" + stateChr + ", descriptionChr="
				+ descriptionChr + ", contactnameChr=" + contactnameChr
				+ ", emailChr=" + emailChr + ", phonenumberChr="
				+ phonenumberChr + ", trxdaylimitNum=" + trxdaylimitNum + "]";
	}

	public String getMtsfield1Chr() {
		return mtsfield1Chr;
	}

	public void setMtsfield1Chr(String mtsfield1Chr) {
		this.mtsfield1Chr = mtsfield1Chr;
	}

	public String getMtsfield2Chr() {
		return mtsfield2Chr;
	}

	public void setMtsfield2Chr(String mtsfield2Chr) {
		this.mtsfield2Chr = mtsfield2Chr;
	}

	public String getMtsfield3Chr() {
		return mtsfield3Chr;
	}

	public void setMtsfield3Chr(String mtsfield3Chr) {
		this.mtsfield3Chr = mtsfield3Chr;
	}

	public String getMtsfield4Chr() {
		return mtsfield4Chr;
	}

	public void setMtsfield4Chr(String mtsfield4Chr) {
		this.mtsfield4Chr = mtsfield4Chr;
	}

	public String getMtsfield5Chr() {
		return mtsfield5Chr;
	}

	public void setMtsfield5Chr(String mtsfield5Chr) {
		this.mtsfield5Chr = mtsfield5Chr;
	}

//    @JsonIgnore
//    @Column(name = "TARGET_WALLET_ID", length = 30)
//    public Long getTargetWalletId() {
//        return targetWalletId;
//    }
//
//    public void setTargetWalletId(Long targetWalletId) {
//        this.targetWalletId = targetWalletId;
//    }

}
