package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import java.io.Serializable;


/**
 * DraftdetailId generated by hbm2java
 */
@Embeddable
public class DraftdetailId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long iddraftPk;
	private Long idbeneficiaryPk;

	public DraftdetailId() {
	}

	public DraftdetailId(Long iddraftPk, Long idbeneficiaryPk) {
		this.iddraftPk = iddraftPk;
		this.idbeneficiaryPk = idbeneficiaryPk;
	}

	@Column(name = "IDDRAFT_PK", nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getIddraftPk() {
		return this.iddraftPk;
	}

	public void setIddraftPk(Long iddraftPk) {
		this.iddraftPk = iddraftPk;
	}

	@Column(name = "IDBENEFICIARY_PK", nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getIdbeneficiaryPk() {
		return this.idbeneficiaryPk;
	}

	public void setIdbeneficiaryPk(Long idbeneficiaryPk) {
		this.idbeneficiaryPk = idbeneficiaryPk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DraftdetailId))
			return false;
		DraftdetailId castOther = (DraftdetailId) other;

		return ((this.getIddraftPk() == castOther.getIddraftPk()) || (this
				.getIddraftPk() != null && castOther.getIddraftPk() != null && this
				.getIddraftPk().equals(castOther.getIddraftPk())))
				&& ((this.getIdbeneficiaryPk() == castOther
						.getIdbeneficiaryPk()) || (this.getIdbeneficiaryPk() != null
						&& castOther.getIdbeneficiaryPk() != null && this
						.getIdbeneficiaryPk().equals(
								castOther.getIdbeneficiaryPk())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIddraftPk() == null ? 0 : this.getIddraftPk().hashCode());
		result = 37
				* result
				+ (getIdbeneficiaryPk() == null ? 0 : this.getIdbeneficiaryPk()
						.hashCode());
		return result;
	}

}
