package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.io.Serializable;
import java.util.Objects;

/**
 * EventcodeId generated by hbm2java
 */
@Embeddable
public class EventcodeId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idprocessPk;
	private Long ideventcodeNum;

	public EventcodeId() {
	}

	public EventcodeId(Long idprocessPk, Long ideventcodeNum) {
		this.idprocessPk = idprocessPk;
		this.ideventcodeNum = ideventcodeNum;
	}

	@Column(name = "IDPROCESS_PK", nullable = false, precision = 4, scale = 0)
	public Long getIdprocessPk() {
		return this.idprocessPk;
	}

	public void setIdprocessPk(Long idprocessPk) {
		this.idprocessPk = idprocessPk;
	}

	@Column(name = "IDEVENTCODE_NUM", nullable = false, precision = 5, scale = 0)
	public Long getIdeventcodeNum() {
		return this.ideventcodeNum;
	}

	public void setIdeventcodeNum(Long ideventcodeNum) {
		this.ideventcodeNum = ideventcodeNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventcodeId))
			return false;
		EventcodeId castOther = (EventcodeId) other;

		return (this.getIdprocessPk() == castOther.getIdprocessPk())
				&& (this.getIdeventcodeNum() == castOther.getIdeventcodeNum());
	}

	@Override
	public int hashCode() {
		return Objects.hash(idprocessPk, ideventcodeNum);
	}
}
