package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import org.hibernate.validator.constraints.Length;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;

/**
 * Logaudit generated by hbm2java
 */
@Entity
@Table(name = "LOGAUDIT")
@EntityListeners(AuditingEntityListener.class)
public class Logaudit implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idlogaudit;
	private User user;
	private String accesstypeChr;
	private String descriptionChr;
	@CreatedBy
	private String usernameChr;
	@CreatedDate
	private Date fechacreacionTim;
	private String paramsChr;
	private String ipChr;

	public Logaudit() {
	}

	public Logaudit(Long idlogaudit) {
		this.idlogaudit = idlogaudit;
	}

	public Logaudit(String accesstypeChr,
			String descriptionChr, String paramsChr, String ipChr) {
		this.accesstypeChr = accesstypeChr;
		this.descriptionChr = descriptionChr;
		this.paramsChr = paramsChr;
		this.ipChr = ipChr;
	}

	@Id
	@Column(name = "IDLOGAUDIT", unique = true, nullable = false, precision = 22, scale = 0)
	@NotNull
	@SequenceGenerator(name="LOGAUDIT_SEQ_GEN",sequenceName="LOGAUDIT_SEQ",allocationSize=1)
	@GeneratedValue(generator="LOGAUDIT_SEQ_GEN")
	public Long getIdlogaudit() {
		return this.idlogaudit;
	}

	public void setIdlogaudit(Long idlogaudit) {
		this.idlogaudit = idlogaudit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUSER_PK")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "ACCESSTYPE_CHR", length = 50)
	@Length(max = 50)
	public String getAccesstypeChr() {
		return this.accesstypeChr;
	}

	public void setAccesstypeChr(String accesstypeChr) {
		this.accesstypeChr = accesstypeChr;
	}

	@Column(name = "DESCRIPTION_CHR", length = 100)
	@Length(max = 100)
	public String getDescriptionChr() {
		return this.descriptionChr;
	}

	public void setDescriptionChr(String descriptionChr) {
		this.descriptionChr = descriptionChr;
	}

	@Column(name = "USERNAME_CHR", length = 100)
	@Length(max = 100)
	public String getUsernameChr() {
		return this.usernameChr;
	}

	public void setUsernameChr(String usernameChr) {
		this.usernameChr = usernameChr;
	}

	@Column(name = "FECHACREACION_TIM")
	public Date getFechacreacionTim() {
		return this.fechacreacionTim;
	}

	public void setFechacreacionTim(Date fechacreacionTim) {
		this.fechacreacionTim = fechacreacionTim;
	}

	@Column(name = "PARAMS_CHR", length = 1500)
	@Length(max = 1500)
	public String getParamsChr() {
		return this.paramsChr;
	}

	public void setParamsChr(String paramsChr) {
		this.paramsChr = paramsChr;
	}

	@Column(name = "IP_CHR", length = 100)
	@Length(max = 100)
	public String getIpChr() {
		return this.ipChr;
	}

	public void setIpChr(String ipChr) {
		this.ipChr = ipChr;
	}

}
