package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;


/**
 * Logmessage generated by hbm2java
 */
@Entity
@Table(name = "LOGMESSAGE" )
public class Logmessage implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idmessagePk;
	private Eventcode eventcode;
	private Company company;
	private Long idpaymentorderPk;
	private Date creationdateTim;
	private String orignumberChr;
	private String destnumberChr;
	private String destemailChr;
	private String messageChr;
	private String notificationeventChr;
	private String transactioncodeChr;
	private String stateChr;
	private long idprocessPk;
	private long ideventcodeNum;

	public Logmessage() {
	}

	public Logmessage(Long idmessagePk, Eventcode eventcode, Company company,
					  Long idpaymentorderPk, Date creationdateTim, String orignumberChr,
					  String destnumberChr, String destemailChr, String messageChr,
					  String notificationeventChr, String transactioncodeChr, String stateChr) {
		this.idmessagePk = idmessagePk;
		this.eventcode = eventcode;
		this.company = company;
		this.idpaymentorderPk = idpaymentorderPk;
		this.creationdateTim = creationdateTim;
		this.orignumberChr = orignumberChr;
		this.destnumberChr = destnumberChr;
		this.destemailChr = destemailChr;
		this.messageChr = messageChr;
		this.notificationeventChr = notificationeventChr;
		this.transactioncodeChr = transactioncodeChr;
		this.stateChr = stateChr;
	}
	public Logmessage(Long idmessagePk, String messageChr, String notificationeventChr,
					  String stateChr, Date creationdateTim){
		this.idmessagePk = idmessagePk;
		this.messageChr = messageChr;
		this.notificationeventChr = notificationeventChr;
		this.stateChr = stateChr;
		this.creationdateTim = creationdateTim;
	}



	@Id
	@NotNull
	@SequenceGenerator(name = "LOGMESSAGE_IDMESSAGEPK_GENERATOR", sequenceName = "LOGMESSAGE_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "LOGMESSAGE_IDMESSAGEPK_GENERATOR")
	@Column(name = "IDMESSAGE_PK", unique = true, nullable = false, precision = 22)
	public Long getIdmessagePk() {
		return this.idmessagePk;
	}

	public void setIdmessagePk(Long idmessagePk) {
		this.idmessagePk = idmessagePk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "IDPROCESS_PK", referencedColumnName = "IDPROCESS_PK",insertable = false, updatable = false),
			@JoinColumn(name = "IDEVENTCODE_NUM", referencedColumnName = "IDEVENTCODE_NUM", insertable = false, updatable = false) })
	public Eventcode getEventcode() {
		return this.eventcode;
	}

	public void setEventcode(Eventcode eventcode) {
		this.eventcode = eventcode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCOMPANY_PK")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "IDPAYMENTORDER_PK", precision = 22, scale = 0)
	public Long getIdpaymentorderPk() {
		return this.idpaymentorderPk;
	}

	public void setIdpaymentorderPk(Long idpaymentorderPk) {
		this.idpaymentorderPk = idpaymentorderPk;
	}

	@Column(name = "CREATIONDATE_TIM", nullable = false)
	public Date getCreationdateTim() {
		return this.creationdateTim;
	}

	public void setCreationdateTim(Date creationdateTim) {
		this.creationdateTim = creationdateTim;
	}

	@Column(name = "ORIGNUMBER_CHR", nullable = true, length = 20, scale = 0)
	@Length(max = 20)
	public String getOrignumberChr() {
		return this.orignumberChr;
	}

	public void setOrignumberChr(String orignumberChr) {
		this.orignumberChr = orignumberChr;
	}

	@Column(name = "DESTNUMBER_CHR")
	@Length(max = 20)
	public String getDestnumberChr() {
		return this.destnumberChr;
	}

	public void setDestnumberChr(String destnumberChr) {
		this.destnumberChr = destnumberChr;
	}
	
	@Column(name = "DESTEMAIL_CHR", nullable = true)
	@Length(max = 200)
	public String getDestemail() {
		return this.destemailChr;
	}

	public void setDestemail(String destemail) {
		this.destemailChr = destemail;
	}

	@Column(name = "MESSAGE_CHR", nullable = false, length = 400)
	@Length(max = 400)
	public String getMessageChr() {
		return this.messageChr;
	}

	public void setMessageChr(String messageChr) {
		this.messageChr = messageChr;
	}

	@Column(name = "NOTIFICATIONEVENT_CHR", nullable = false, length = 100)
	@Length(max = 100)
	public String getNotificationeventChr() {
		return this.notificationeventChr;
	}

	public void setNotificationeventChr(String notificationeventChr) {
		this.notificationeventChr = notificationeventChr;
	}

	@Column(name = "STATE_CHR", nullable = false, length = 2)
	public String getStateChr() {
		return this.stateChr;
	}

	public void setStateChr(String stateChr) {
		this.stateChr = stateChr;
	}

	@Column(name = "TRANSACTIONCODE_CHR", nullable = true, length = 30)
	public String getTransactioncodeChr() {
		return transactioncodeChr;
	}

	public void setTransactioncodeChr(String transactioncodeChr) {
		this.transactioncodeChr = transactioncodeChr;
	}

	@Column(name = "IDPROCESS_PK", nullable = false)
	public Long getIdprocessPk() {
		return idprocessPk;
	}
	public void setIdprocessPk(long idprocessPk) {
		this.idprocessPk = idprocessPk;
	}
	@Column(name = "IDEVENTCODE_NUM", nullable = false)
	public Long getIdeventcodeNum() {
		return ideventcodeNum;
	}

	public void setIdeventcodeNum(long ideventcodeNum) {
		this.ideventcodeNum = ideventcodeNum;
	}

	@Override
	public String toString() {
		return "Logmessage{" +
				"idmessagePk=" + idmessagePk +
				", idCompany=" + (company!=null?company.getIdcompanyPk():"") +
				", idpaymentorderPk=" + idpaymentorderPk +
				", creationdateTim=" + creationdateTim +
				", orignumberChr='" + orignumberChr + '\'' +
				", destnumberChr='" + destnumberChr + '\'' +
				", destemailChr='" + destemailChr + '\'' +
				", messageChr='" + messageChr + '\'' +
				", notificationeventChr='" + notificationeventChr + '\'' +
				", transactioncodeChr='" + transactioncodeChr + '\'' +
				", stateChr=" + stateChr +
				", idprocessPk=" + idprocessPk +
				'}';
	}
}
