package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;


/**
 * Logmtsrev generated by hbm2java
 */
@Entity
@Table(name = "LOGMTSREV")
public class Logmtsrev implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idlogmtsrevPk;
	private Paymentorderdetail paymentorderdetail;
	private Eventcode eventcode;
	private Company company;
	private Logpayment logpayment;
	private Logmts logmts;
	private Date requestdateTim;
	private Date responsedateTim;
	private String requestChr;
	private String responseChr;
	private String methodChr;
	private String trxtypeChr;
	private BigDecimal amountNum;
	private String amountChr;
	private String stateChr;
	private String idtrxmtsChr;
	private String idsessionmtsChr;
	private Long idprocessPk;
	private Long ideventcodeNum;


	public Logmtsrev() {
	}

	public Logmtsrev(String idlogmtsrevPk,
			Paymentorderdetail paymentorderdetail, Eventcode eventcode,
			Company company, Logpayment logpayment, Logmts logmts,
			Date requestdateTim, Date responsedateTim, String requestChr,
			String responseChr, String methodChr, String trxtypeChr,
			BigDecimal amountNum, String  stateChr) {
		this.idlogmtsrevPk = idlogmtsrevPk;
		this.paymentorderdetail = paymentorderdetail;
		this.eventcode = eventcode;
		this.company = company;
		this.logpayment = logpayment;
		this.logmts = logmts;
		this.requestdateTim = requestdateTim;
		this.responsedateTim = responsedateTim;
		this.requestChr = requestChr;
		this.responseChr = responseChr;
		this.methodChr = methodChr;
		this.trxtypeChr = trxtypeChr;
		this.amountNum = amountNum;
		this.stateChr = stateChr;
	}

	public Logmtsrev(String idlogmtsrevPk, Paymentorderdetail paymentorderdetail,
					 Eventcode eventcode, Company company, Logpayment logpayment,
					 Logmts logmts, Date requestdateTim, Date responsedateTim,
					 String requestChr, String responseChr, String methodChr,
					 String trxtypeChr, BigDecimal amountNum, String amountChr,
					 String stateChr, String idtrxmtsChr, String idsessionmtsChr) {
		this.idlogmtsrevPk = idlogmtsrevPk;
		this.paymentorderdetail = paymentorderdetail;
		this.eventcode = eventcode;
		this.company = company;
		this.logpayment = logpayment;
		this.logmts = logmts;
		this.requestdateTim = requestdateTim;
		this.responsedateTim = responsedateTim;
		this.requestChr = requestChr;
		this.responseChr = responseChr;
		this.methodChr = methodChr;
		this.trxtypeChr = trxtypeChr;
		this.amountNum = amountNum;
		this.amountChr = amountChr;
		this.stateChr = stateChr;
		this.idtrxmtsChr = idtrxmtsChr;
		this.idsessionmtsChr = idsessionmtsChr;
	}

	@Id
	@SequenceGenerator(name="LOGMTSREV_IDLOGMTSREVPK_GENERATOR", sequenceName="LOGMTSREV_SEQ", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="LOGMTSREV_IDLOGMTSREVPK_GENERATOR")
	@Column(name = "IDLOGMTSREV_PK", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getIdlogmtsrevPk() {
		return this.idlogmtsrevPk;
	}

	public void setIdlogmtsrevPk(String idlogmtsrevPk) {
		this.idlogmtsrevPk = idlogmtsrevPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "IDPAYMENTORDER_PK", referencedColumnName = "IDPAYMENTORDER_PK", nullable = false),
			@JoinColumn(name = "IDBENEFICIARY_PK", referencedColumnName = "IDBENEFICIARY_PK", nullable = false) })
	@NotNull
	public Paymentorderdetail getPaymentorderdetail() {
		return this.paymentorderdetail;
	}

	public void setPaymentorderdetail(Paymentorderdetail paymentorderdetail) {
		this.paymentorderdetail = paymentorderdetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "IDPROCESS_PK", referencedColumnName = "IDPROCESS_PK", nullable = false),
			@JoinColumn(name = "IDEVENTCODE_NUM", referencedColumnName = "IDEVENTCODE_NUM", nullable = false) })
	@NotNull
	public Eventcode getEventcode() {
		return this.eventcode;
	}

	public void setEventcode(Eventcode eventcode) {
		this.eventcode = eventcode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCOMPANY_PK", nullable = false)
	@NotNull
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPAYMENT_NUM", nullable = false)
	@NotNull
	public Logpayment getLogpayment() {
		return this.logpayment;
	}

	public void setLogpayment(Logpayment logpayment) {
		this.logpayment = logpayment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDLOGMTS_PK", nullable = false)
	@NotNull
	public Logmts getLogmts() {
		return this.logmts;
	}

	public void setLogmts(Logmts logmts) {
		this.logmts = logmts;
	}

	@Column(name = "REQUESTDATE_TIM", nullable = false)
	@NotNull
	public Date getRequestdateTim() {
		return this.requestdateTim;
	}

	public void setRequestdateTim(Date requestdateTim) {
		this.requestdateTim = requestdateTim;
	}

	@Column(name = "RESPONSEDATE_TIM", nullable = false)
	@NotNull
	public Date getResponsedateTim() {
		return this.responsedateTim;
	}

	public void setResponsedateTim(Date responsedateTim) {
		this.responsedateTim = responsedateTim;
	}

	@Column(name = "REQUEST_CHR", nullable = false, length = 400)
	@NotNull
	@Length(max = 400)
	public String getRequestChr() {
		return this.requestChr;
	}

	public void setRequestChr(String requestChr) {
		this.requestChr = requestChr;
	}

	@Column(name = "RESPONSE_CHR", nullable = false, length = 400)
	@NotNull
	@Length(max = 400)
	public String getResponseChr() {
		return this.responseChr;
	}

	public void setResponseChr(String responseChr) {
		this.responseChr = responseChr;
	}

	@Column(name = "METHOD_CHR", nullable = false, length = 40)
	@NotNull
	@Length(max = 40)
	public String getMethodChr() {
		return this.methodChr;
	}

	public void setMethodChr(String methodChr) {
		this.methodChr = methodChr;
	}

	@Column(name = "TRXTYPE_CHR", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getTrxtypeChr() {
		return this.trxtypeChr;
	}

	public void setTrxtypeChr(String trxtypeChr) {
		this.trxtypeChr = trxtypeChr;
	}

	@Column(name = "AMOUNT_CHR", nullable = false, length = 48)
	@NotNull
	public String getAmountChr() {
		return this.amountChr;
	}

	public void setAmountChr(String amountChr) {
		this.amountChr = amountChr;
	}

	@Transient
	public BigDecimal getAmountNum() {
		return new BigDecimal(this.amountChr);
	}

	public void setAmountNum(BigDecimal amountNum) {
		this.amountChr=amountNum.toPlainString();
	}

	@Column(name = "STATE_CHR", nullable = false, length = 2)
	public String getStateChr() {
		return this.stateChr;
	}

	public void setStateChr(String stateChr) {
		this.stateChr = stateChr;
	}

	@Column(name = "IDTRXMTS_CHR", length = 20)
	@Length(max = 20)
	public String getIdtrxmtsChr() {
		return this.idtrxmtsChr;
	}

	public void setIdtrxmtsChr(String idtrxmtsChr) {
		this.idtrxmtsChr = idtrxmtsChr;
	}


	@Column(name="IDSESSIONMTS_CHR", nullable=false, length=50)
	public String getIdsessionmtsChr() {
		return idsessionmtsChr;
	}

	public void setIdsessionmtsChr(String idsessionmtsChr) {
		this.idsessionmtsChr = idsessionmtsChr;
	}

	@Column(name = "IDPROCESS_PK", insertable = false, updatable = false)
	public Long getIdprocessPk() {
		return idprocessPk;
	}

	public void setIdprocessPk(Long idprocessPk) {
		this.idprocessPk = idprocessPk;
	}

	@Column(name = "IDEVENTCODE_NUM", insertable = false, updatable = false)
	public Long getIdeventcodeNum() {
		return ideventcodeNum;
	}

	public void setIdeventcodeNum(Long ideventcodeNum) {
		this.ideventcodeNum = ideventcodeNum;
	}


	@Override
	public String toString() {
		final StringBuffer sb = new StringBuffer("Logmtsrev{");
		sb.append("idlogmtsrevPk='").append(idlogmtsrevPk).append('\'');
		sb.append(", idPaymentorderdetail=").append(paymentorderdetail.getId());
		sb.append(", idEventcode=").append(eventcode.getId());
		sb.append(", idCompany=").append(company.getIdcompanyPk());
		sb.append(", idLogpayment=").append(logpayment.getIdpaymentNum());
		sb.append(", idLogmts=").append(logmts.getIdlogmtsPk());
		sb.append(", requestdateTim=").append(requestdateTim);
		sb.append(", responsedateTim=").append(responsedateTim);
		sb.append(", requestChr='").append(requestChr).append('\'');
		sb.append(", responseChr='").append(responseChr).append('\'');
		sb.append(", methodChr='").append(methodChr).append('\'');
		sb.append(", trxtypeChr='").append(trxtypeChr).append('\'');
		sb.append(", amountNum=").append(amountNum);
		sb.append(", amountChr='").append(amountChr).append('\'');
		sb.append(", stateChr=").append(stateChr);
		sb.append(", idtrxmtsChr='").append(idtrxmtsChr).append('\'');
		sb.append(", idsessionmtsChr='").append(idsessionmtsChr).append('\'');
		sb.append('}');
		return sb.toString();
	}
}
