package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1


import org.hibernate.validator.constraints.Length;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import javax.persistence.*;

import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;


/**
 * Logsession generated by hbm2java
 */
@Entity
@Table(name = "LOGSESSION" )
@EntityListeners(AuditingEntityListener.class)
public class Logsession implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idlogPk;
	private String userChr;
	private Boolean successloginNum;
	@CreatedDate
	private Date logindateTim;
	private String messageChr;
	private String ipChr;

	public Logsession() {
	}

	public Logsession(Long idlogPk, String userChr,
			Boolean successloginNum, Date logindateTim) {
		this.idlogPk = idlogPk;
		this.userChr = userChr;
		this.successloginNum = successloginNum;
		this.logindateTim = logindateTim;
	}

	public Logsession(Long idlogPk, String userChr,
			Boolean successloginNum, Date logindateTim,
			String messageChr) {
		this.idlogPk = idlogPk;
		this.userChr = userChr;
		this.successloginNum = successloginNum;
		this.logindateTim = logindateTim;
		this.messageChr = messageChr;
	}

		
	@Id
	@Column(name = "IDLOG_PK", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name="LOGSESSION_SEQ_GEN",sequenceName="LOGSESSION_SEQ",allocationSize=1)
	@GeneratedValue(generator="LOGSESSION_SEQ_GEN")
	@NotNull
	public Long getIdlogPk() {
		return this.idlogPk;
	}

	public void setIdlogPk(Long idlogPk) {
		this.idlogPk = idlogPk;
	}

	@Column(name = "USER_CHR", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUserChr() {
		return this.userChr;
	}

	public void setUserChr(String userChr) {
		this.userChr = userChr;
	}

	@Column(name = "SUCCESSLOGIN_NUM", nullable = false, precision = 1, scale = 0)
	public Boolean isSuccessloginNum() {
		return this.successloginNum;
	}

	public void setSuccessloginNum(Boolean successloginNum) {
		this.successloginNum = successloginNum;
	}

	@Column(name = "LOGINDATE_TIM", nullable = false)
	@NotNull
	public Date getLogindateTim() {
		return this.logindateTim;
	}

	public void setLogindateTim(Date logindateTim) {
		this.logindateTim = logindateTim;
	}

	@Column(name = "MESSAGE_CHR", length = 200)
	@Length(max = 200)
	public String getMessageChr() {
		return this.messageChr;
	}

	public void setMessageChr(String messageChr) {
		this.messageChr = messageChr;
	}

	@Column(name = "IP_CHR", length = 100)
	@Length(max = 100)
	public String getIpChr() {
		return ipChr;
	}

	public void setIpChr(String ipChr) {
		this.ipChr = ipChr;
	}

}
