package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;
import org.hibernate.validator.constraints.Length;
import py.com.global.spm.domain.utils.ScopeViews;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;


/**
 * Paymentordertype generated by hbm2java
 */
@Entity
@Table(name = "PAYMENTORDERTYPE" )
public class Paymentordertype implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idorderpaymenttypePk;
	private String nameChr;
	private String descriptionChr;
	private Set<Paymentorder> paymentorders = new HashSet<Paymentorder>(0);
	private Set<Draft> drafts = new HashSet<Draft>(0);

	public Paymentordertype() {
	}

	public Paymentordertype(Long idorderpaymenttypePk, String nameChr) {
		this.idorderpaymenttypePk = idorderpaymenttypePk;
		this.nameChr = nameChr;
	}

	public Paymentordertype(Long idorderpaymenttypePk, String nameChr,
			String descriptionChr, Set<Paymentorder> paymentorders,
			Set<Draft> drafts) {
		this.idorderpaymenttypePk = idorderpaymenttypePk;
		this.nameChr = nameChr;
		this.descriptionChr = descriptionChr;
		this.paymentorders = paymentorders;
		this.drafts = drafts;
	}

	@Id
	@Column(name = "IDPAYMENTORDERTYPE_PK", unique = true, nullable = false, precision = 22, scale = 0)
	@NotNull
	@JsonView({ScopeViews.Basics.class})
	@SequenceGenerator(name="PAYMENTORDERTYPE_SEQ_GEN",sequenceName="PAYMENTORDERTYPE_SEQ",allocationSize=1)
	@GeneratedValue(generator="PAYMENTORDERTYPE_SEQ_GEN")
	public Long getIdorderpaymenttypePk() {
		return this.idorderpaymenttypePk;
	}

	public void setIdorderpaymenttypePk(Long idorderpaymenttypePk) {
		this.idorderpaymenttypePk = idorderpaymenttypePk;
	}

	@Column(name = "NAME_CHR", nullable = false, length = 30)
	@NotNull
	@JsonView({ScopeViews.Basics.class})
	@Length(max = 30)
	public String getNameChr() {
		return this.nameChr;
	}

	public void setNameChr(String nameChr) {
		this.nameChr = nameChr;
	}

	@JsonView({ScopeViews.Basics.class})
	@Column(name = "DESCRIPTION_CHR", length = 100)
	@Length(max = 100)
	public String getDescriptionChr() {
		return this.descriptionChr;
	}

	public void setDescriptionChr(String descriptionChr) {
		this.descriptionChr = descriptionChr;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentordertype")
	public Set<Paymentorder> getPaymentorders() {
		return this.paymentorders;
	}

	public void setPaymentorders(Set<Paymentorder> paymentorders) {
		this.paymentorders = paymentorders;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentordertype")
	public Set<Draft> getDrafts() {
		return this.drafts;
	}

	public void setDrafts(Set<Draft> drafts) {
		this.drafts = drafts;
	}


}
