package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import java.io.Serializable;


/**
 * PaymentorderdetailId generated by hbm2java
 */
@Embeddable
public class PaymentorderdetailId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idpaymentorderPk;
	private Long idbeneficiaryPk;

	public PaymentorderdetailId() {
	}

	public PaymentorderdetailId(Long idpaymentorderPk,
			Long idbeneficiaryPk) {
		this.idpaymentorderPk = idpaymentorderPk;
		this.idbeneficiaryPk = idbeneficiaryPk;
	}

	@Column(name = "IDPAYMENTORDER_PK", nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getIdpaymentorderPk() {
		return this.idpaymentorderPk;
	}

	public void setIdpaymentorderPk(Long idpaymentorderPk) {
		this.idpaymentorderPk = idpaymentorderPk;
	}

	@Column(name = "IDBENEFICIARY_PK", nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getIdbeneficiaryPk() {
		return this.idbeneficiaryPk;
	}

	public void setIdbeneficiaryPk(Long idbeneficiaryPk) {
		this.idbeneficiaryPk = idbeneficiaryPk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaymentorderdetailId))
			return false;
		PaymentorderdetailId castOther = (PaymentorderdetailId) other;

		return ((this.getIdpaymentorderPk() == castOther.getIdpaymentorderPk()) || (this
				.getIdpaymentorderPk() != null
				&& castOther.getIdpaymentorderPk() != null && this
				.getIdpaymentorderPk().equals(castOther.getIdpaymentorderPk())))
				&& ((this.getIdbeneficiaryPk() == castOther
						.getIdbeneficiaryPk()) || (this.getIdbeneficiaryPk() != null
						&& castOther.getIdbeneficiaryPk() != null && this
						.getIdbeneficiaryPk().equals(
								castOther.getIdbeneficiaryPk())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdpaymentorderPk() == null ? 0 : this
						.getIdpaymentorderPk().hashCode());
		result = 37
				* result
				+ (getIdbeneficiaryPk() == null ? 0 : this.getIdbeneficiaryPk()
						.hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "PaymentorderdetailId{" +
				"idpaymentorderPk=" + idpaymentorderPk +
				", idbeneficiaryPk=" + idbeneficiaryPk +
				'}';
	}
}
