package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import org.hibernate.validator.constraints.Length;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import java.io.Serializable;


/**
 * ProcesscontrolId generated by hbm2java
 */
@Embeddable
public class ProcesscontrolId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String serverPk;
	private Long idprocessPk;

	public ProcesscontrolId() {
	}

	public ProcesscontrolId(String serverPk, Long idprocessPk) {
		this.serverPk = serverPk;
		this.idprocessPk = idprocessPk;
	}

	@Column(name = "SERVER_PK", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getServerPk() {
		return this.serverPk;
	}

	public void setServerPk(String serverPk) {
		this.serverPk = serverPk;
	}

	@Column(name = "IDPROCESS_PK", nullable = false, precision = 4, scale = 0)
	public Long getIdprocessPk() {
		return this.idprocessPk;
	}

	public void setIdprocessPk(Long idprocessPk) {
		this.idprocessPk = idprocessPk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcesscontrolId))
			return false;
		ProcesscontrolId castOther = (ProcesscontrolId) other;

		return ((this.getServerPk() == castOther.getServerPk()) || (this
				.getServerPk() != null && castOther.getServerPk() != null && this
				.getServerPk().equals(castOther.getServerPk())))
				&& (this.getIdprocessPk() == castOther.getIdprocessPk());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getServerPk() == null ? 0 : this.getServerPk().hashCode());
		result = 37 * result + this.getIdprocessPk().intValue();
		return result;
	}

}
