package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;


/**
 * Processcontrol generated by hbm2java
 */
@Entity
@Table(name = "PROCESSCONTROL" )
public class Processcontrol implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ProcesscontrolId id;
	private Process process;
	private Date creationdateTim;
	private Date changedateTim;
	private Boolean runnit;
	private Boolean running;
	private String descripcion;

	public Processcontrol() {
	}

	public Processcontrol(ProcesscontrolId id, Process process) {
		this.id = id;
		this.process = process;
	}

	public Processcontrol(ProcesscontrolId id, Process process,
			Date creationdateTim, Date changedateTim,
			Boolean runnit, Boolean running, String descripcion) {
		this.id = id;
		this.process = process;
		this.creationdateTim = creationdateTim;
		this.changedateTim = changedateTim;
		this.runnit = runnit;
		this.running = running;
		this.descripcion = descripcion;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "serverPk", column = @Column(name = "SERVER_PK", nullable = false, length = 30)),
			@AttributeOverride(name = "idprocessPk", column = @Column(name = "IDPROCESS_PK", nullable = false, precision = 4, scale = 0)) })
	@NotNull
	public ProcesscontrolId getId() {
		return this.id;
	}

	public void setId(ProcesscontrolId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPROCESS_PK", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Process getProcess() {
		return this.process;
	}

	public void setProcess(Process process) {
		this.process = process;
	}

	@Column(name = "CREATIONDATE_TIM")
	public Date getCreationdateTim() {
		return this.creationdateTim;
	}

	public void setCreationdateTim(Date creationdateTim) {
		this.creationdateTim = creationdateTim;
	}

	@Column(name = "CHANGEDATE_TIM")
	public Date getChangedateTim() {
		return this.changedateTim;
	}

	public void setChangedateTim(Date changedateTim) {
		this.changedateTim = changedateTim;
	}

	@Column(name = "RUNNIT", precision = 1, scale = 0)
	public Boolean getRunnit() {
		return this.runnit;
	}

	public void setRunnit(Boolean runnit) {
		this.runnit = runnit;
	}

	@Column(name = "RUNNING", precision = 1, scale = 0)
	public Boolean getRunning() {
		return this.running;
	}

	public void setRunning(Boolean running) {
		this.running = running;
	}

	@Column(name = "DESCRIPCION", length = 30)
	@Length(max = 30)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


	@Override
	public String toString() {
		final StringBuffer sb = new StringBuffer("Processcontrol{");
		sb.append("id=").append(id);
		sb.append(", idProcess=").append(process.getIdprocessPk());
		sb.append(", creationdateTim=").append(creationdateTim);
		sb.append(", changedateTim=").append(changedateTim);
		sb.append(", runnit=").append(runnit);
		sb.append(", running=").append(running);
		sb.append(", descripcion='").append(descripcion).append('\'');
		sb.append('}');
		return sb.toString();
	}
}
