package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import org.hibernate.validator.constraints.Length;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Objects;


/**
 * SystemparameterId generated by hbm2java
 */
@Embeddable
public class SystemparameterId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String parameterPk;
	private Long idprocessPk;

	public SystemparameterId() {
	}

	public SystemparameterId(String parameterPk, Long idprocessPk) {
		this.parameterPk = parameterPk;
		this.idprocessPk = idprocessPk;
	}

	@Column(name = "PARAMETER_PK", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getParameterPk() {
		return this.parameterPk;
	}

	public void setParameterPk(String parameterPk) {
		this.parameterPk = parameterPk;
	}

	@Column(name = "IDPROCESS_PK", nullable = false, precision = 4, scale = 0)
	public Long getIdprocessPk() {
		return this.idprocessPk;
	}

	public void setIdprocessPk(Long idprocessPk) {
		this.idprocessPk = idprocessPk;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;
		SystemparameterId that = (SystemparameterId) o;
		return Objects.equals(parameterPk, that.parameterPk) &&
				Objects.equals(idprocessPk, that.idprocessPk);
	}

	@Override
	public int hashCode() {
		return Objects.hash(parameterPk, idprocessPk);
	}

	@Override
	public String toString() {
		return "SystemparameterId{" +
				"parameterPk='" + parameterPk + '\'' +
				", idprocessPk=" + idprocessPk +
				'}';
	}
}
