package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import org.hibernate.validator.constraints.Length;
import py.com.global.spm.domain.audit.EntityAuditEventListener;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;

/**
 * Systemparameter generated by hbm2java
 */
@Entity
@Table(name = "SYSTEMPARAMETER" )
@EntityListeners(EntityAuditEventListener.class)
public class Systemparameter implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private SystemparameterId id;
	private Process process;
	private String valueChr;
	private String descripcionChr;
	private Date creationdateTim;

	public Systemparameter() {
	}

	public Systemparameter(SystemparameterId id, Process process,
			String valueChr, Date creationdateTim) {
		this.id = id;
		this.process = process;
		this.valueChr = valueChr;
		this.creationdateTim = creationdateTim;
	}

	public Systemparameter(SystemparameterId id, Process process,
			String valueChr, String descripcionChr, Date creationdateTim) {
		this.id = id;
		this.process = process;
		this.valueChr = valueChr;
		this.descripcionChr = descripcionChr;
		this.creationdateTim = creationdateTim;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "parameterPk", column = @Column(name = "PARAMETER_PK", nullable = false, length = 50)),
			@AttributeOverride(name = "idprocessPk", column = @Column(name = "IDPROCESS_PK", nullable = false, precision = 4, scale = 0)) })
	@NotNull
	public SystemparameterId getId() {
		return this.id;
	}

	public void setId(SystemparameterId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPROCESS_PK", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Process getProcess() {
		return this.process;
	}

	public void setProcess(Process process) {
		this.process = process;
	}

	@Column(name = "VALUE_CHR", nullable = false, length = 400)
	@NotNull
	@Length(max = 400)
	public String getValueChr() {
		return this.valueChr;
	}

	public void setValueChr(String valueChr) {
		this.valueChr = valueChr;
	}

	@Column(name = "DESCRIPCION_CHR", length = 100)
	@Length(max = 100)
	public String getDescripcionChr() {
		return this.descripcionChr;
	}

	public void setDescripcionChr(String descripcionChr) {
		this.descripcionChr = descripcionChr;
	}

	@Column(name = "CREATIONDATE_TIM", nullable = false)
	@NotNull
	public Date getCreationdateTim() {
		return this.creationdateTim;
	}

	public void setCreationdateTim(Date creationdateTim) {
		this.creationdateTim = creationdateTim;
	}

	@Override
	public String toString() {
		return "Systemparameter{" +
				"id=" + id.getParameterPk() +
				", process=" + process.getProcessnameChr() +
				", valueChr='" + valueChr + '\'' +
				", descripcionChr='" + descripcionChr + '\'' +
				", creationdateTim=" + creationdateTim +
				'}';
	}
}
