package py.com.global.spm.domain.entity;

// Generated 15/07/2013 09:59:46 AM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonView;
import py.com.global.spm.domain.utils.ScopeViews;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import java.io.Serializable;


/**
 * WorkflowdetId generated by hbm2java
 */
@Embeddable
public class WorkflowdetId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long iduserPk;
	private Long idworkflowPk;

	public WorkflowdetId() {
	}

	public WorkflowdetId(Long iduserPk,
			Long idworkflowPk) {
		this.iduserPk = iduserPk;
		this.idworkflowPk = idworkflowPk;
	}
	@JsonView({ScopeViews.NoBasics.class})
	@Column(name = "IDUSER_PK", nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getIduserPk() {
		return this.iduserPk;
	}

	public void setIduserPk(Long iduserPk) {
		this.iduserPk = iduserPk;
	}

	@JsonView({ScopeViews.NoBasics.class})
	@Column(name = "IDWORKFLOW_PK", nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getIdworkflowPk() {
		return this.idworkflowPk;
	}

	public void setIdworkflowPk(Long idworkflowPk) {
		this.idworkflowPk = idworkflowPk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkflowdetId))
			return false;
		WorkflowdetId castOther = (WorkflowdetId) other;

		return (this.getIduserPk() == castOther.getIduserPk()) || (this
						.getIduserPk() != null
						&& castOther.getIduserPk() != null && this
						.getIduserPk().equals(castOther.getIduserPk()))
				&& ((this.getIdworkflowPk() == castOther.getIdworkflowPk()) || (this
						.getIdworkflowPk() != null
						&& castOther.getIdworkflowPk() != null && this
						.getIdworkflowPk().equals(castOther.getIdworkflowPk())));
	}

	public int hashCode() {
		int result = 17;

		
		result = 37 * result
				+ (getIduserPk() == null ? 0 : this.getIduserPk().hashCode());
		result = 37
				* result
				+ (getIdworkflowPk() == null ? 0 : this.getIdworkflowPk()
						.hashCode());
		return result;
	}

	@Override
	public String toString() {
		final StringBuffer sb = new StringBuffer("WorkflowdetId{");
		sb.append("iduserPk=").append(iduserPk);
		sb.append(", idworkflowPk=").append(idworkflowPk);
		sb.append('}');
		return sb.toString();
	}
}
