server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript,text/csv
# JACKSON
spring:
  transaction:
    default-timeout: 1800
  jackson:
    serialization:
      INDENT_OUTPUT: true
      fail-on-empty-beans: false
    date-format: yyyy-MM-dd
    time-zone: America/Asuncion
  #mail:
   # host: smtp.gmail.com
    #username: unacuentamas16@gmail.com
    #password: unacuentamas
    #properties:
     # mail:
      #  smtp:
       #   auth: true
        #  socketFactory:
         #   port: 465
          #  class: javax.net.ssl.SSLSocketFactory
           # fallback: false
          #starttls:
           # enable: true
          #ssl:
           # enable: true
  #DATASOURCEs
  datasource:
    #jndi-name: java:jboss/datasources/SPM-GUIDatasource
    url: jdbc:oracle:thin:@192.168.0.40:1521:XE
    username: GOPMFS_TEST
    password: GOPMFS_TEST
  jpa:
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
#    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework:
      security: INFO
      web: INFO
    org.hibernate: ERROR
    org.apache.catalina:
      valves.RemoteIpValve: DEBUG
    io.swagger.models.parameters.AbstractSerializableParameter: error

jwt:
  header: Authorization
  secret: gl0balSI
  expiration: 1800  # 30 MINUTOS
  route:
    authentication:
      path: auth
      refresh: refresh
swagger:
  security:
    client-id: bulkpayment-01
    client-secret: bulkpayment-glObal
    realm: app-bulpayment-realm
    appName: app-bulkpayment
recovery:
  link: "[SCHEME]://[IP]:[PORT][CONTEXT_PATH]/#/changePassword?token=[TOKEN]"
amount:
  encrypt:
    password: 00SiStEmAdEpAgOm
    enabled: false





