package py.com.global.spm.GUISERVICE.enums;


import py.com.global.spm.GUISERVICE.utils.GeneralHelper;

public enum EventNotificationsEnum {

	//INACTIVE('I',"state_INACTIVE");
	//NOMBRE_ENUM("CODIGO","DESCRIPCION -> MESSAGES_PROPERTIES")
	NOTIFY_SIGNER_EMAIL("SIGNER_EMAIL","NOTIFY_SIGNER_EMAIL"),
	NOTIFY_SIGNER_SMS("SIGNER_SMS","NOTIFY_SIGNER_SMS"),
	NOTIFY_PAYMENT_BENEFICIARY("PAYMENT_BENEFICIARY","NOTIFY_PAYMENT_BENEFICIARY"),
	NOTIFY_PO_CREATED("PAYMENT_ORDER_CREATED","NOTIFY_PO_CREATED"),
	NOTIFY_PO_CANCELLED("PAYMENT_ORDER_CANCELLED","NOTIFY_PO_CANCELLED"),
	NOTIFY_INSUFFICIENT_MONEY("INSUFFICIENT_MONEY","NOTIFY_INSUFFICIENT_MONEY"),
	NOTIFY_PO_REVERSION("PAYMENT_ORDER_REVERSION","NOTIFY_PO_REVERSION"),
	NOTIFY_PO_PARTIAL_REVERSION("PO_PARTIAL_REVERSION","NOTIFY_PO_PARTIAL_REVERSION"),
	NOTIFY_PO_UNREVERSION("PO_UNREVERSION","NOTIFY_PO_UNREVERSION"),
	NOTIFY_PO_UNPAID("PAYMENT_ORDER_UNPAID","NOTIFY_PO_UNPAID"),
	NOTIFY_PO_SIGNATURE_SUCCESS("PO_SIGNATURE_SUCCESS","NOTIFY_PO_SIGNATURE_SUCCESS"),
	NOTIFY_SIGNER_BLOCK("SIGNER_BLOCK","NOTIFY_SIGNER_BLOCK"),
	NOTIFY_VALID_TIME("VALID_TIME","NOTIFY_VALID_TIME"),
	NOTIFY_OP_GENERATION_FAILED("PAYMENT_ORDER_GENERATION_FAILED","NOTIFY_OP_GENERATION_FAILED"),
	NOTIFY_INCORRECT_PIN("INCORRECT_PIN","NOTIFY_INCORRECT_PIN"),
	NOTIFY_PASS_RECOVERY("PASS_RECOVERY","NOTIFY_PASS_RECOVERY"),
	NOTIFY_USER_CREATED("USER_CREATED","NOTIFY_USER_CREATED"),
	NOTIFY_OUTTIME_APPROVAL("OUTTIME_APPROVAL","NOTIFY_OUTTIME_APPROVAL"),
	NOTIFY_PAYMENT_ORDER_NOT_FOUND("PAYMENT_ORDER_NOT_FOUND","NOTIFY_PAYMENT_ORDER_NOT_FOUND"),
	NOTIFY_INVALID_PAYMENT_ORDER_STATE("INVALID_PAYMENT_ORDER_STATE","NOTIFY_INVALID_PAYMENT_ORDER_STATE"),
	NOTIFY_NOT_SIGNER_TURN("NOT_SIGNER_TURN","NOTIFY_NOT_SIGNER_TURN"),
	NOTIFY_INCORRECT_PIN_LAST_CHANCE("INCORRECT_PIN_LAST_CHANCE","NOTIFY_INCORRECT_PIN_LAST_CHANCE"),
	NOTIFY_INCORRECT_PIN_USER_BLOCKED("INCORRECT_PIN_USER_BLOCKED","NOTIFY_INCORRECT_PIN_USER_BLOCKED"),
	NOTIFY_INVALID_MESSAGE("INVALID_MESSAGE","NOTIFY_INVALID_MESSAGE"),
	NOTIFY_UNKNOW_USER("UNKNOW_USER","NOTIFY_UNKNOW_USER"),
	NOTIFY_UNKNOW_DESTINATION("UNKNOW_DESTINATION","NOTIFY_UNKNOW_DESTINATION"),
	NOTIFY_UNKNOW_USER_PREFIX("UNKNOW_USER_PREFIX","NOTIFY_UNKNOW_USER_PREFIX"),
	NOTIFY_INVALID_ID_PAYMENT_ORDER("INVALID_ID_PAYMENT_ORDER","NOTIFY_INVALID_ID_PAYMENT_ORDER"),
	NOTIFY_OTHER_ERROR("OTHER_ERROR","NOTIFY_OTHER_ERROR"),
	NOTIFY_PAYMENT_SIGNERS("PAYMENT_SIGNERS","NOTIFY_PAYMENT_SIGNERS"),
	NOTIFY_SIGNEVENT("NOTIFY_SIGNEVENT","NOTIFY_SIGNEVENT"),
	NO_NOTIFIED("UNNOTIFIED","UNNOTIFIED");
	
	String codigo0;
	String descriptionOrKeyMsg;
	
	private EventNotificationsEnum(String codigo0, String descriptionOrKeyMsg) {
		this.codigo0 = codigo0;
		this.descriptionOrKeyMsg = descriptionOrKeyMsg;
	}

	public String getCodigo0() {
		return codigo0;
	}

//	public String getDescriptionOrKeyMsg() {
//		return GeneralHelper.getMessages(descriptionOrKeyMsg);
//	}

//	@Override
//	public String toString() {
//		return getDescriptionOrKeyMsg();
//	}
	

}
