
package us.inswitch.mts.ws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MTS", targetNamespace = "http://server.ws.mts.inswitch.us/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MTS {


    /**
     * 
     * @param pwd
     * @param role
     * @param usr
     * @param ip
     * @return
     *     returns us.inswitch.mts.ws.server.BindPack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bind", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.Bind")
    @ResponseWrapper(localName = "bindResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.BindResponse")
    public BindPack bind(
        @WebParam(name = "usr", targetNamespace = "")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "")
        String pwd,
        @WebParam(name = "role", targetNamespace = "")
        String role,
        @WebParam(name = "ip", targetNamespace = "")
        String ip);

    /**
     * 
     * @param theString
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "identity", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.Identity")
    @ResponseWrapper(localName = "identityResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.IdentityResponse")
    public String identity(
        @WebParam(name = "theString", targetNamespace = "")
        String theString);

    /**
     * 
     * @param sesion
     * @param documentoRemitente
     * @param msisdnSuscriptor
     * @return
     *     returns us.inswitch.mts.ws.server.PinPack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resetPin", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.ResetPin")
    @ResponseWrapper(localName = "resetPinResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.ResetPinResponse")
    public PinPack resetPin(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "msisdn_suscriptor", targetNamespace = "")
        String msisdnSuscriptor,
        @WebParam(name = "documento_remitente", targetNamespace = "")
        String documentoRemitente);

    /**
     * 
     * @param sesion
     * @return
     *     returns us.inswitch.mts.ws.server.UnBindPack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unBind", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.UnBind")
    @ResponseWrapper(localName = "unBindResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.UnBindResponse")
    public UnBindPack unBind(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion);

    /**
     * 
     * @param sesion
     * @return
     *     returns us.inswitch.mts.ws.server.UsuarioPack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "usuario", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.Usuario")
    @ResponseWrapper(localName = "usuarioResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.UsuarioResponse")
    public UsuarioPack usuario(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion);

    /**
     * 
     * @param sesion
     * @return
     *     returns us.inswitch.mts.ws.server.RolPack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rol", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.Rol")
    @ResponseWrapper(localName = "rolResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.RolResponse")
    public RolPack rol(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion);

    /**
     * 
     * @param sesion
     * @return
     *     returns us.inswitch.mts.ws.server.CotizacionPack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cotizacion", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.Cotizacion")
    @ResponseWrapper(localName = "cotizacionResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CotizacionResponse")
    public CotizacionPack cotizacion(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion);

    /**
     * 
     * @param sesion
     * @return
     *     returns us.inswitch.mts.ws.server.SaldoPack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaSaldo", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.ConsultaSaldo")
    @ResponseWrapper(localName = "consultaSaldoResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.ConsultaSaldoResponse")
    public SaldoPack consultaSaldo(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion);

    /**
     * 
     * @param fechaIniAnho
     * @param sesion
     * @param fechaFinAnho
     * @param fechaFinDia
     * @param fechaFinMes
     * @param fechaIniDia
     * @param fechaIniMes
     * @return
     *     returns us.inswitch.mts.ws.server.MovBilleteraPack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "movBilletera", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.MovBilletera")
    @ResponseWrapper(localName = "movBilleteraResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.MovBilleteraResponse")
    public MovBilleteraPack movBilletera(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "fecha_ini_anho", targetNamespace = "")
        String fechaIniAnho,
        @WebParam(name = "fecha_ini_mes", targetNamespace = "")
        String fechaIniMes,
        @WebParam(name = "fecha_ini_dia", targetNamespace = "")
        String fechaIniDia,
        @WebParam(name = "fecha_fin_anho", targetNamespace = "")
        String fechaFinAnho,
        @WebParam(name = "fecha_fin_mes", targetNamespace = "")
        String fechaFinMes,
        @WebParam(name = "fecha_fin_dia", targetNamespace = "")
        String fechaFinDia);

    /**
     * 
     * @param idTransaccion
     * @param sesion
     * @return
     *     returns us.inswitch.mts.ws.server.TransaccionPack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTrn", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.ConsultaTrn")
    @ResponseWrapper(localName = "consultaTrnResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.ConsultaTrnResponse")
    public TransaccionPack consultaTrn(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "id_transaccion", targetNamespace = "")
        Integer idTransaccion);

    /**
     * 
     * @param nuevoPin
     * @param actualPin
     * @param sesion
     * @return
     *     returns us.inswitch.mts.ws.server.PinPack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cambioPin", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CambioPin")
    @ResponseWrapper(localName = "cambioPinResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CambioPinResponse")
    public PinPack cambioPin(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "actual_pin", targetNamespace = "")
        String actualPin,
        @WebParam(name = "nuevo_pin", targetNamespace = "")
        String nuevoPin);

    /**
     * 
     * @param cuentaDestino
     * @param sesion
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.BasicResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cashInPre", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashInPre")
    @ResponseWrapper(localName = "cashInPreResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashInPreResponse")
    public BasicResponsePack cashInPre(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_destino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto);

    /**
     * 
     * @param cuentaDestino
     * @param sesion
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.TrnResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cashInConfirm", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashInConfirm")
    @ResponseWrapper(localName = "cashInConfirmResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashInConfirmResponse")
    public TrnResponsePack cashInConfirm(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_destino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto);

    /**
     * 
     * @param fechaNacimientoCliente
     * @param documentoCliente
     * @param cuentaCliente
     * @param sesion
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.BasicResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cashOutPre", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashOutPre")
    @ResponseWrapper(localName = "cashOutPreResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashOutPreResponse")
    public BasicResponsePack cashOutPre(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_cliente", targetNamespace = "")
        String cuentaCliente,
        @WebParam(name = "documento_cliente", targetNamespace = "")
        String documentoCliente,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto,
        @WebParam(name = "fecha_nacimiento_cliente", targetNamespace = "")
        XMLGregorianCalendar fechaNacimientoCliente);

    /**
     * 
     * @param documentoCliente
     * @param cuentaCliente
     * @param sesion
     * @param fechaNacimiento
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.TrnResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cashOutConfirm", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashOutConfirm")
    @ResponseWrapper(localName = "cashOutConfirmResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashOutConfirmResponse")
    public TrnResponsePack cashOutConfirm(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_cliente", targetNamespace = "")
        String cuentaCliente,
        @WebParam(name = "documento_cliente", targetNamespace = "")
        String documentoCliente,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto,
        @WebParam(name = "fecha_nacimiento", targetNamespace = "")
        XMLGregorianCalendar fechaNacimiento);

    /**
     * 
     * @param cuentaDestino
     * @param sesion
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.BasicResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cashInPreEscrow", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashInPreEscrow")
    @ResponseWrapper(localName = "cashInPreEscrowResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashInPreEscrowResponse")
    public BasicResponsePack cashInPreEscrow(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_destino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto);

    /**
     * 
     * @param cuentaDestino
     * @param sesion
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.TrnResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cashInConfirmEscrow", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashInConfirmEscrow")
    @ResponseWrapper(localName = "cashInConfirmEscrowResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashInConfirmEscrowResponse")
    public TrnResponsePack cashInConfirmEscrow(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_destino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto);

    /**
     * 
     * @param fechaNacimientoCliente
     * @param documentoCliente
     * @param cuentaCliente
     * @param sesion
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.BasicResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cashOutPreEscrow", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashOutPreEscrow")
    @ResponseWrapper(localName = "cashOutPreEscrowResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashOutPreEscrowResponse")
    public BasicResponsePack cashOutPreEscrow(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_cliente", targetNamespace = "")
        String cuentaCliente,
        @WebParam(name = "documento_cliente", targetNamespace = "")
        String documentoCliente,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto,
        @WebParam(name = "fecha_nacimiento_cliente", targetNamespace = "")
        XMLGregorianCalendar fechaNacimientoCliente);

    /**
     * 
     * @param documentoCliente
     * @param cuentaCliente
     * @param sesion
     * @param fechaNacimiento
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.TrnResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cashOutConfirmEscrow", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashOutConfirmEscrow")
    @ResponseWrapper(localName = "cashOutConfirmEscrowResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CashOutConfirmEscrowResponse")
    public TrnResponsePack cashOutConfirmEscrow(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_cliente", targetNamespace = "")
        String cuentaCliente,
        @WebParam(name = "documento_cliente", targetNamespace = "")
        String documentoCliente,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto,
        @WebParam(name = "fecha_nacimiento", targetNamespace = "")
        XMLGregorianCalendar fechaNacimiento);

    /**
     * 
     * @param cuentaDestino
     * @param sesion
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.BasicResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remitPre", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.RemitPre")
    @ResponseWrapper(localName = "remitPreResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.RemitPreResponse")
    public BasicResponsePack remitPre(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_destino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto);

    /**
     * 
     * @param cuentaDestino
     * @param sesion
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.TrnResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remitConfirm", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.RemitConfirm")
    @ResponseWrapper(localName = "remitConfirmResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.RemitConfirmResponse")
    public TrnResponsePack remitConfirm(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_destino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto);

    /**
     * 
     * @param cuentaDestino
     * @param documento
     * @param sesion
     * @param cuentaRemitente
     * @param fechaNacimiento
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.BasicResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remitNationalPre", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.RemitNationalPre")
    @ResponseWrapper(localName = "remitNationalPreResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.RemitNationalPreResponse")
    public BasicResponsePack remitNationalPre(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_remitente", targetNamespace = "")
        String cuentaRemitente,
        @WebParam(name = "cuenta_destino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto,
        @WebParam(name = "documento", targetNamespace = "")
        String documento,
        @WebParam(name = "fecha_nacimiento", targetNamespace = "")
        XMLGregorianCalendar fechaNacimiento);

    /**
     * 
     * @param cuentaDestino
     * @param documento
     * @param sesion
     * @param cuentaRemitente
     * @param fechaNacimiento
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.TrnResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remitNationalConfirm", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.RemitNationalConfirm")
    @ResponseWrapper(localName = "remitNationalConfirmResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.RemitNationalConfirmResponse")
    public TrnResponsePack remitNationalConfirm(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_remitente", targetNamespace = "")
        String cuentaRemitente,
        @WebParam(name = "cuenta_destino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto,
        @WebParam(name = "documento", targetNamespace = "")
        String documento,
        @WebParam(name = "fecha_nacimiento", targetNamespace = "")
        XMLGregorianCalendar fechaNacimiento);

    /**
     * 
     * @param cuentaDestino
     * @param idTransaccion
     * @param documento
     * @param sesion
     * @param cuentaRemitente
     * @param fechaNacimiento
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.TrnResponsePack
     */
    @WebMethod(operationName = "remitNational_ModifyTransaction")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remitNational_ModifyTransaction", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.RemitNationalModifyTransaction")
    @ResponseWrapper(localName = "remitNational_ModifyTransactionResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.RemitNationalModifyTransactionResponse")
    public TrnResponsePack remitNationalModifyTransaction(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "id_transaccion", targetNamespace = "")
        String idTransaccion,
        @WebParam(name = "cuenta_remitente", targetNamespace = "")
        String cuentaRemitente,
        @WebParam(name = "cuenta_destino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto,
        @WebParam(name = "documento", targetNamespace = "")
        String documento,
        @WebParam(name = "fecha_nacimiento", targetNamespace = "")
        XMLGregorianCalendar fechaNacimiento);

    /**
     * 
     * @param sesion
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.BasicResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selfTopUpPre", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.SelfTopUpPre")
    @ResponseWrapper(localName = "selfTopUpPreResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.SelfTopUpPreResponse")
    public BasicResponsePack selfTopUpPre(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto);

    /**
     * 
     * @param sesion
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.TrnResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selfTopUpConfirm", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.SelfTopUpConfirm")
    @ResponseWrapper(localName = "selfTopUpConfirmResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.SelfTopUpConfirmResponse")
    public TrnResponsePack selfTopUpConfirm(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto);

    /**
     * 
     * @param cuentaDestino
     * @param sesion
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.BasicResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cobroPre", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CobroPre")
    @ResponseWrapper(localName = "cobroPreResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CobroPreResponse")
    public BasicResponsePack cobroPre(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_destino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto);

    /**
     * 
     * @param cuentaDestino
     * @param sesion
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.TrnResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cobroConfirm", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CobroConfirm")
    @ResponseWrapper(localName = "cobroConfirmResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.CobroConfirmResponse")
    public TrnResponsePack cobroConfirm(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_destino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto);

    /**
     * 
     * @param cuentaDestino
     * @param moneda
     * @param brand
     * @param sesion
     * @param rolPredeterminado
     * @param tipoBilletera
     * @param monto
     * @return
     *     returns us.inswitch.mts.ws.server.TrnResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "salaryPayment", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.SalaryPayment")
    @ResponseWrapper(localName = "salaryPaymentResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.SalaryPaymentResponse")
    public TrnResponsePack salaryPayment(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "cuenta_destino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "rol_predeterminado", targetNamespace = "")
        String rolPredeterminado,
        @WebParam(name = "monto", targetNamespace = "")
        Double monto,
        @WebParam(name = "moneda", targetNamespace = "")
        String moneda,
        @WebParam(name = "brand", targetNamespace = "")
        String brand,
        @WebParam(name = "tipo_billetera", targetNamespace = "")
        String tipoBilletera);

    /**
     * 
     * @param idTransaccion
     * @param sesion
     * @return
     *     returns us.inswitch.mts.ws.server.TrnResponsePack
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "agentAutoReversion", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.AgentAutoReversion")
    @ResponseWrapper(localName = "agentAutoReversionResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.AgentAutoReversionResponse")
    public TrnResponsePack agentAutoReversion(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "id_transaccion", targetNamespace = "")
        String idTransaccion);

    /**
     * 
     * @param servicio
     * @param sesion
     * @param xml
     * @param codigoEntidad
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServiceParameter", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.GetServiceParameter")
    @ResponseWrapper(localName = "getServiceParameterResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.GetServiceParameterResponse")
    public String getServiceParameter(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "servicio", targetNamespace = "")
        Integer servicio,
        @WebParam(name = "codigo_entidad", targetNamespace = "")
        String codigoEntidad,
        @WebParam(name = "xml", targetNamespace = "")
        String xml)
        throws Exception_Exception
    ;

    /**
     * 
     * @param servicio
     * @param sesion
     * @param xml
     * @param codigoEntidad
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "serviceParameter", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.ServiceParameter")
    @ResponseWrapper(localName = "serviceParameterResponse", targetNamespace = "http://server.ws.mts.inswitch.us/", className = "us.inswitch.mts.ws.server.ServiceParameterResponse")
    public String serviceParameter(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "servicio", targetNamespace = "")
        Integer servicio,
        @WebParam(name = "codigo_entidad", targetNamespace = "")
        String codigoEntidad,
        @WebParam(name = "xml", targetNamespace = "")
        String xml)
        throws Exception_Exception
    ;

}
