
package us.inswitch.mts.ws.server;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MTSService", targetNamespace = "http://server.ws.mts.inswitch.us/", wsdlLocation = "file:/C:/Users/R2/Desktop/naranja/MTSGW-TSYSTEM.wsdl")
public class MTSService
    extends Service
{

    private final static URL MTSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(us.inswitch.mts.ws.server.MTSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = us.inswitch.mts.ws.server.MTSService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/R2/Desktop/naranja/MTSGW-TSYSTEM.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/R2/Desktop/naranja/MTSGW-TSYSTEM.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MTSSERVICE_WSDL_LOCATION = url;
    }

    public MTSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MTSService() {
        super(MTSSERVICE_WSDL_LOCATION, new QName("http://server.ws.mts.inswitch.us/", "MTSService"));
    }

    /**
     * 
     * @return
     *     returns MTS
     */
    @WebEndpoint(name = "MTSPort")
    public MTS getMTSPort() {
        return super.getPort(new QName("http://server.ws.mts.inswitch.us/", "MTSPort"), MTS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MTS
     */
    @WebEndpoint(name = "MTSPort")
    public MTS getMTSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.ws.mts.inswitch.us/", "MTSPort"), MTS.class, features);
    }

}
